# Generated by Django 3.0.1 on 2020-05-24 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_organisation_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='active',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель записи'),
        ),
    ]
